Update tag names for ecdsa and eddsa test suites and add `supportedEcdsaKeyTypes` property to ` ecdsa-rdfc-2019` implementations
w3c/vc-test-suite-implementations pull request #5
Opened 2023-11-17 20:52 UTC by JSAssassin

2023-11-20 16:07 UTC, dlongley approved these changes

2023-11-20 21:42 UTC, BigBlueHat requested changes
Update readme with latest links and clearer formatting--especially calling out the new `supportedEcdsaKeyTypes` property.

2023-11-20 21:42 UTC, BigBlueHat commented on README.md
> +`vc2.0` - This tag will run the [VC Data Model 2.0 Test Suite](https://github.com/digitalbazaar/vc-data-model-2-test-suite) on your issuer and verifier endpoints.
```suggestion
* `vc2.0` - This tag will run the [VC Data Model 2.0 Test Suite](https://github.com/w3c/vc-data-model-2.0-test-suite) on your issuer and verifier endpoints.
```

2023-11-20 21:42 UTC, BigBlueHat commented on README.md
> +`Ed25519Signature2020` - This tag will run the [Ed25519 tests](https://github.com/w3c-ccg/di-ed25519-test-suite) on either your issuer and/or verifier.
```suggestion
* `Ed25519Signature2020` - This tag will run the [Ed25519 tests](https://github.com/w3c/vc-di-ed25519signature2020-test-suite) on either your issuer and/or verifier.
```

2023-11-20 21:42 UTC, BigBlueHat commented on README.md
> +types.
```suggestion
* `ecdsa-rdfc-2019` or `ecdsa-sd-2023` - These tags will run the
[VC Data Integrity ECDSA Test Suite](https://github.com/w3c/vc-di-ecdsa-test-suite)
on your issuer and verifier endpoints.
  * Alongside this cryptosuite tag, you must also specify the `supportedEcdsaKeyTypes`
  key parallel to `tags` listing the ECDSA key types that your implementation issues or
  can verify. Currently, the test suite supports `P-256` and `P-384` ECDSA key types.
```

2023-11-20 21:42 UTC, BigBlueHat commented on README.md
> +`eddsa-rdfc-2022` - This tag will run the [VC Data Integrity EDDSA Test Suite](https://github.com/w3c-ccg/di-eddsa-2022-test-suite) on your issuer and verifier endpoints.
```suggestion
* `eddsa-rdfc-2022` - This tag will run the [VC Data Integrity EDDSA Test Suite](https://github.com/w3c/vc-di-eddsa-test-suite) on your issuer and verifier endpoints.
```

2023-11-27 17:03 UTC, JSAssassin commented
Updated readme with latest links and clearer formatting here [26eed46](https://github.com/w3c/vc-test-suite-implementations/pull/5/commits/26eed466abb5cac325ab2b7037519e3f7c432b4e)

2023-11-27 17:10 UTC, BigBlueHat approved these changes

2023-11-27 21:07 UTC, aljones15 approved these changes
good

2023-11-27 21:08 UTC, merged