Add checks to db verifier.
w3c/vc-test-suite-implementations pull request #52
Opened 2024-07-26 20:16 UTC by aljones15

@PatStLouis @BigBlueHat adds `options.checks = ['poof']` to the db verifier endpoint.
This is how we usually let implementers specify options that have been deprecated by the VC API, but 
they haven't had the time or resources to correct on their endpoints.

2024-07-26 21:09 UTC, PatStLouis approved these changes

2024-07-29 16:23 UTC, BigBlueHat approved these changes

2024-07-29 16:33 UTC, BigBlueHat requested changes
@aljones15 fwiw, these are also being used on the `vpVerifier` endpoints in the VCDMv2 test suite:
https://github.com/w3c/vc-data-model-2.0-test-suite/blob/00fa18a7b676959e7aa5e4b8774a7ce049f9c0d0/tests/10-vcdm2.js#L214
and
https://github.com/w3c/vc-data-model-2.0-test-suite/blob/00fa18a7b676959e7aa5e4b8774a7ce049f9c0d0/tests/10-vcdm2.js#L809

2024-07-29 17:21 UTC, aljones15 commented
> @aljones15 fwiw, these are also being used on the `vpVerifier` endpoints in the VCDMv2 test suite: https://github.com/w3c/vc-data-model-2.0-test-suite/blob/00fa18a7b676959e7aa5e4b8774a7ce049f9c0d0/tests/10-vcdm2.js#L214 and https://github.com/w3c/vc-data-model-2.0-test-suite/blob/00fa18a7b676959e7aa5e4b8774a7ce049f9c0d0/tests/10-vcdm2.js#L809

good call here will make those changes in a moment.

2024-07-30 15:35 UTC, BigBlueHat approved these changes

2024-07-30 15:42 UTC, merged