Add envelope issuer to DB issuers.
w3c/vc-test-suite-implementations pull request #58
Opened 2024-09-18 18:05 UTC by aljones15

2024-09-23 17:17 UTC, PatStLouis requested changes

2024-09-23 17:17 UTC, PatStLouis commented on implementations/DigitalBazaar.json
> +     "tags": ["VC-ENVELOPE"]
```suggestion
     "tags": ["EnvelopingProof"]
```

2024-09-24 00:00 UTC, PatStLouis approved these changes

2024-09-24 00:22 UTC, tminard approved these changes

2024-09-24 14:43 UTC, merged