Update ApiCatalog manifest
w3c/vc-test-suite-implementations pull request #80
Opened 2024-11-24 19:11 UTC by filip26

Hi, 
added JCS issuers + updated endpoints.
Thank you!

2024-12-02 21:12 UTC, BigBlueHat approved these changes

2024-12-03 21:38 UTC, PatStLouis requested changes

2024-12-03 21:38 UTC, PatStLouis commented on implementations/ApiCatalog.json
> +      "id": "ttps://us-central1-api-catalog.cloudfunctions.net/vc-api-issue-eddsa-jcs-2022",
```suggestion
      "id": "ttps://us-central1-api-catalog.cloudfunctions.net/vc-api-issue-eddsa-jcs-2022",
```
```suggestion
      "id": "https://us-central1-api-catalog.cloudfunctions.net/vc-api-issue-eddsa-jcs-2022",
```

2024-12-03 21:39 UTC, filip26 commented on implementations/ApiCatalog.json
> +      "id": "ttps://us-central1-api-catalog.cloudfunctions.net/vc-api-issue-eddsa-jcs-2022",
@PatStLouis thank you,  good catch!

2024-12-05 16:27 UTC, PatStLouis approved these changes

2024-12-05 16:27 UTC, merged